image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

build-job-dev:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:latest  .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - develop

deploy-dev:
  stage: deploy
  image: alpine
  variables:
    DEPLOY_PATH: /home/ec2-user/nest-pnr-template
    EC2: $EC2_DEV
    SSH_PRIVATE_KEY: $ID_RSA
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no ./docker-compose.yml $EC2:$DEPLOY_PATH
    - ssh -o StrictHostKeyChecking=no $EC2 "cd $DEPLOY_PATH && docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY && docker-compose down --rmi all && docker-compose up -d"
  only:
    - develop
 